name: Release workflow
on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-maven-ghactions-release
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout main branch
      run: git checkout main
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jogog/ci_test
        tag_with_ref: true
    
    
